# Generated by Django 5.0.1 on 2024-01-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VACANCIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Front-end developer', 'Front-end developer'), ('Back-end developer', 'Back-end developer'), ('Fullstack developer', 'Fullstack developer'), ('SQL developer', 'Fullstack developer'), ('HR Trainee', 'HR Trainee')], max_length=30, null=True)),
                ('Vacancies', models.CharField(max_length=10, null=True)),
                ('Locations', models.CharField(max_length=50, null=True)),
                ('Experience', models.CharField(max_length=30, null=True)),
                ('skills', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
